package database

func a2zSheet() sheetData {
	return sheetData{
		Name:        "A2Z DSA Sheet",
		Slug:        "a2z-sheet",
		Description: "Master DSA from Basics to Advanced",
		Topics: []topicData{
			{Name: "Know Basic Maths", Problems: []problemData{
				{"Count Digits", "https://leetcode.com/problems/number-of-digits-that-divide-a-number/", "Easy"},
				{"Reverse a Number", "https://leetcode.com/problems/reverse-integer/", "Medium"},
				{"Check Palindrome", "https://leetcode.com/problems/palindrome-number/", "Easy"},
				{"GCD of Two Numbers", "https://leetcode.com/problems/find-greatest-common-divisor-of-array/", "Easy"},
				{"Armstrong Number", "https://www.geeksforgeeks.org/program-for-armstrong-numbers/", "Easy"},
				{"Print all Divisors", "https://www.geeksforgeeks.org/find-all-divisors-of-a-natural-number-set-2/", "Easy"},
				{"Check for Prime", "https://www.geeksforgeeks.org/prime-numbers/", "Easy"},
			}},
			{Name: "Learn Basic Recursion", Problems: []problemData{
				{"Print 1 to N using Recursion", "https://www.geeksforgeeks.org/print-1-to-n-without-using-loops/", "Easy"},
				{"Print N to 1 using Recursion", "https://www.geeksforgeeks.org/print-numbers-1-n-using-recursion/", "Easy"},
				{"Sum of First N Numbers", "https://www.geeksforgeeks.org/sum-of-natural-numbers-using-recursion/", "Easy"},
				{"Factorial of N", "https://leetcode.com/problems/factorial-trailing-zeroes/", "Easy"},
				{"Reverse an Array", "https://leetcode.com/problems/reverse-string/", "Easy"},
				{"Check if String is Palindrome", "https://leetcode.com/problems/valid-palindrome/", "Easy"},
				{"Fibonacci Number", "https://leetcode.com/problems/fibonacci-number/", "Easy"},
			}},
			{Name: "Sorting Techniques", Problems: []problemData{
				{"Selection Sort", "https://www.geeksforgeeks.org/selection-sort/", "Easy"},
				{"Bubble Sort", "https://www.geeksforgeeks.org/bubble-sort/", "Easy"},
				{"Insertion Sort", "https://www.geeksforgeeks.org/insertion-sort/", "Easy"},
				{"Merge Sort", "https://leetcode.com/problems/sort-an-array/", "Medium"},
				{"Quick Sort", "https://www.geeksforgeeks.org/quick-sort/", "Medium"},
			}},
			{Name: "Arrays - Easy", Problems: []problemData{
				{"Largest Element in Array", "https://www.geeksforgeeks.org/c-program-find-largest-element-array/", "Easy"},
				{"Second Largest Element", "https://www.geeksforgeeks.org/find-second-largest-element-array/", "Easy"},
				{"Check if Array is Sorted", "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/", "Easy"},
				{"Remove Duplicates from Sorted Array", "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", "Easy"},
				{"Left Rotate Array by One", "https://www.geeksforgeeks.org/array-rotation/", "Easy"},
				{"Left Rotate Array by K Places", "https://leetcode.com/problems/rotate-array/", "Medium"},
				{"Move Zeros to End", "https://leetcode.com/problems/move-zeroes/", "Easy"},
				{"Linear Search", "https://www.geeksforgeeks.org/linear-search/", "Easy"},
				{"Union of Two Sorted Arrays", "https://www.geeksforgeeks.org/union-and-intersection-of-two-sorted-arrays-2/", "Easy"},
				{"Missing Number", "https://leetcode.com/problems/missing-number/", "Easy"},
				{"Maximum Consecutive Ones", "https://leetcode.com/problems/max-consecutive-ones/", "Easy"},
				{"Single Number", "https://leetcode.com/problems/single-number/", "Easy"},
				{"Longest Subarray with Sum K (Positives)", "https://www.geeksforgeeks.org/longest-sub-array-sum-k/", "Medium"},
			}},
			{Name: "Arrays - Medium", Problems: []problemData{
				{"Two Sum", "https://leetcode.com/problems/two-sum/", "Easy"},
				{"Sort an array of 0's 1's and 2's", "https://leetcode.com/problems/sort-colors/", "Medium"},
				{"Majority Element", "https://leetcode.com/problems/majority-element/", "Easy"},
				{"Kadane's Algorithm", "https://leetcode.com/problems/maximum-subarray/", "Medium"},
				{"Print Subarray with Max Sum", "https://leetcode.com/problems/maximum-subarray/", "Medium"},
				{"Stock Buy and Sell", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Easy"},
				{"Rearrange Array by Sign", "https://leetcode.com/problems/rearrange-array-elements-by-sign/", "Medium"},
				{"Next Permutation", "https://leetcode.com/problems/next-permutation/", "Medium"},
				{"Leaders in an Array", "https://www.geeksforgeeks.org/leaders-in-an-array/", "Easy"},
				{"Longest Consecutive Sequence", "https://leetcode.com/problems/longest-consecutive-sequence/", "Medium"},
				{"Set Matrix Zeroes", "https://leetcode.com/problems/set-matrix-zeroes/", "Medium"},
				{"Rotate Image", "https://leetcode.com/problems/rotate-image/", "Medium"},
				{"Spiral Matrix", "https://leetcode.com/problems/spiral-matrix/", "Medium"},
				{"Count Subarrays with Given Sum", "https://leetcode.com/problems/subarray-sum-equals-k/", "Medium"},
			}},
			{Name: "Arrays - Hard", Problems: []problemData{
				{"Pascal's Triangle", "https://leetcode.com/problems/pascals-triangle/", "Easy"},
				{"Majority Element II", "https://leetcode.com/problems/majority-element-ii/", "Medium"},
				{"3 Sum", "https://leetcode.com/problems/3sum/", "Medium"},
				{"4 Sum", "https://leetcode.com/problems/4sum/", "Medium"},
				{"Largest Subarray with Sum 0", "https://www.geeksforgeeks.org/find-the-largest-subarray-with-0-sum/", "Medium"},
				{"Count Subarrays with XOR K", "https://www.geeksforgeeks.org/count-number-subarrays-given-xor/", "Hard"},
				{"Merge Overlapping Subintervals", "https://leetcode.com/problems/merge-intervals/", "Medium"},
				{"Merge Two Sorted Arrays Without Extra Space", "https://leetcode.com/problems/merge-sorted-array/", "Easy"},
				{"Find the Repeating and Missing Number", "https://www.geeksforgeeks.org/find-a-repeating-and-a-missing-number/", "Medium"},
				{"Count Inversions", "https://www.geeksforgeeks.org/counting-inversions/", "Hard"},
				{"Reverse Pairs", "https://leetcode.com/problems/reverse-pairs/", "Hard"},
				{"Maximum Product Subarray", "https://leetcode.com/problems/maximum-product-subarray/", "Medium"},
			}},
			{Name: "Binary Search - 1D Arrays", Problems: []problemData{
				{"Binary Search", "https://leetcode.com/problems/binary-search/", "Easy"},
				{"Lower Bound", "https://www.geeksforgeeks.org/lower-bound-in-a-sorted-array/", "Easy"},
				{"Upper Bound", "https://www.geeksforgeeks.org/upper-bound-in-a-sorted-array/", "Easy"},
				{"Search Insert Position", "https://leetcode.com/problems/search-insert-position/", "Easy"},
				{"Floor and Ceil", "https://www.geeksforgeeks.org/floor-in-a-sorted-array/", "Easy"},
				{"First and Last Occurrence", "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", "Medium"},
				{"Count Occurrences in Sorted Array", "https://www.geeksforgeeks.org/count-number-of-occurrences-or-frequency-in-a-sorted-array/", "Easy"},
				{"Search in Rotated Sorted Array I", "https://leetcode.com/problems/search-in-rotated-sorted-array/", "Medium"},
				{"Search in Rotated Sorted Array II", "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/", "Medium"},
				{"Find Minimum in Rotated Sorted Array", "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", "Medium"},
				{"Single Element in Sorted Array", "https://leetcode.com/problems/single-element-in-a-sorted-array/", "Medium"},
				{"Find Peak Element", "https://leetcode.com/problems/find-peak-element/", "Medium"},
			}},
			{Name: "Binary Search - Answers", Problems: []problemData{
				{"Find Square Root", "https://leetcode.com/problems/sqrtx/", "Easy"},
				{"Find Nth Root of Integer", "https://www.geeksforgeeks.org/n-th-root-number/", "Medium"},
				{"Koko Eating Bananas", "https://leetcode.com/problems/koko-eating-bananas/", "Medium"},
				{"Minimum Days to Make M Bouquets", "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/", "Medium"},
				{"Find the Smallest Divisor", "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/", "Medium"},
				{"Capacity to Ship Packages", "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", "Medium"},
				{"Kth Missing Positive Number", "https://leetcode.com/problems/kth-missing-positive-number/", "Easy"},
				{"Aggressive Cows", "https://www.spoj.com/problems/AGGRCOW/", "Hard"},
				{"Book Allocation Problem", "https://www.geeksforgeeks.org/allocate-minimum-number-pages/", "Hard"},
				{"Split Array Largest Sum", "https://leetcode.com/problems/split-array-largest-sum/", "Hard"},
				{"Painter's Partition", "https://www.geeksforgeeks.org/painters-partition-problem/", "Hard"},
				{"Median of Two Sorted Arrays", "https://leetcode.com/problems/median-of-two-sorted-arrays/", "Hard"},
				{"Kth Element of Two Sorted Arrays", "https://www.geeksforgeeks.org/k-th-element-two-sorted-arrays/", "Medium"},
			}},
			{Name: "Binary Search - 2D Arrays", Problems: []problemData{
				{"Row with Maximum 1's", "https://www.geeksforgeeks.org/find-the-row-with-maximum-number-1s/", "Easy"},
				{"Search in a 2D Matrix", "https://leetcode.com/problems/search-a-2d-matrix/", "Medium"},
				{"Search in a 2D Matrix II", "https://leetcode.com/problems/search-a-2d-matrix-ii/", "Medium"},
				{"Find Peak Element II", "https://leetcode.com/problems/find-a-peak-element-ii/", "Medium"},
				{"Matrix Median", "https://www.geeksforgeeks.org/find-median-row-wise-sorted-matrix/", "Hard"},
			}},
			{Name: "Strings - Basic", Problems: []problemData{
				{"Remove Outermost Parentheses", "https://leetcode.com/problems/remove-outermost-parentheses/", "Easy"},
				{"Reverse Words in String", "https://leetcode.com/problems/reverse-words-in-a-string/", "Medium"},
				{"Largest Odd Number in String", "https://leetcode.com/problems/largest-odd-number-in-string/", "Easy"},
				{"Longest Common Prefix", "https://leetcode.com/problems/longest-common-prefix/", "Easy"},
				{"Isomorphic Strings", "https://leetcode.com/problems/isomorphic-strings/", "Easy"},
				{"Rotate String", "https://leetcode.com/problems/rotate-string/", "Easy"},
				{"Check Anagram", "https://leetcode.com/problems/valid-anagram/", "Easy"},
			}},
			{Name: "Strings - Medium", Problems: []problemData{
				{"Sort Characters by Frequency", "https://leetcode.com/problems/sort-characters-by-frequency/", "Medium"},
				{"Maximum Nesting Depth of Parentheses", "https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/", "Easy"},
				{"Roman to Integer", "https://leetcode.com/problems/roman-to-integer/", "Easy"},
				{"String to Integer (atoi)", "https://leetcode.com/problems/string-to-integer-atoi/", "Medium"},
				{"Longest Palindromic Substring", "https://leetcode.com/problems/longest-palindromic-substring/", "Medium"},
				{"Sum of Beauty of All Substrings", "https://leetcode.com/problems/sum-of-beauty-of-all-substrings/", "Medium"},
			}},
			{Name: "Linked List - Basics", Problems: []problemData{
				{"Introduction to Linked List", "https://www.geeksforgeeks.org/what-is-linked-list/", "Easy"},
				{"Inserting a Node in Linked List", "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/", "Easy"},
				{"Deleting a Node in Linked List", "https://leetcode.com/problems/delete-node-in-a-linked-list/", "Medium"},
				{"Find Length of Linked List", "https://www.geeksforgeeks.org/find-length-of-a-linked-list-iterative-and-recursive/", "Easy"},
				{"Search in Linked List", "https://www.geeksforgeeks.org/search-an-element-in-a-linked-list-iterative-and-recursive/", "Easy"},
			}},
			{Name: "Linked List - Medium", Problems: []problemData{
				{"Middle of Linked List", "https://leetcode.com/problems/middle-of-the-linked-list/", "Easy"},
				{"Reverse Linked List", "https://leetcode.com/problems/reverse-linked-list/", "Easy"},
				{"Detect Cycle in Linked List", "https://leetcode.com/problems/linked-list-cycle/", "Easy"},
				{"Starting Point of Cycle", "https://leetcode.com/problems/linked-list-cycle-ii/", "Medium"},
				{"Length of Loop", "https://www.geeksforgeeks.org/find-length-of-loop-in-linked-list/", "Easy"},
				{"Check Palindrome Linked List", "https://leetcode.com/problems/palindrome-linked-list/", "Easy"},
				{"Odd Even Linked List", "https://leetcode.com/problems/odd-even-linked-list/", "Medium"},
				{"Remove Nth Node from End", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "Medium"},
				{"Delete Middle Node", "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/", "Medium"},
				{"Sort Linked List", "https://leetcode.com/problems/sort-list/", "Medium"},
				{"Intersection of Two Linked Lists", "https://leetcode.com/problems/intersection-of-two-linked-lists/", "Easy"},
				{"Add Two Numbers", "https://leetcode.com/problems/add-two-numbers/", "Medium"},
			}},
			{Name: "Linked List - Hard", Problems: []problemData{
				{"Reverse Nodes in k-Group", "https://leetcode.com/problems/reverse-nodes-in-k-group/", "Hard"},
				{"Rotate List", "https://leetcode.com/problems/rotate-list/", "Medium"},
				{"Flattening a Linked List", "https://www.geeksforgeeks.org/flattening-a-linked-list/", "Medium"},
				{"Clone Linked List with Random Pointer", "https://leetcode.com/problems/copy-list-with-random-pointer/", "Medium"},
			}},
			{Name: "Recursion & Backtracking", Problems: []problemData{
				{"Subsets", "https://leetcode.com/problems/subsets/", "Medium"},
				{"Subsets II", "https://leetcode.com/problems/subsets-ii/", "Medium"},
				{"Combination Sum", "https://leetcode.com/problems/combination-sum/", "Medium"},
				{"Combination Sum II", "https://leetcode.com/problems/combination-sum-ii/", "Medium"},
				{"Permutations", "https://leetcode.com/problems/permutations/", "Medium"},
				{"Palindrome Partitioning", "https://leetcode.com/problems/palindrome-partitioning/", "Medium"},
				{"N Queens", "https://leetcode.com/problems/n-queens/", "Hard"},
				{"Sudoku Solver", "https://leetcode.com/problems/sudoku-solver/", "Hard"},
				{"M Coloring Problem", "https://www.geeksforgeeks.org/m-coloring-problem-backtracking-5/", "Medium"},
				{"Rat in a Maze", "https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-2/", "Medium"},
				{"Word Break", "https://leetcode.com/problems/word-break/", "Medium"},
			}},
			{Name: "Bit Manipulation", Problems: []problemData{
				{"Count Set Bits", "https://leetcode.com/problems/number-of-1-bits/", "Easy"},
				{"Check if ith Bit is Set", "https://www.geeksforgeeks.org/check-whether-k-th-bit-is-set-or-not/", "Easy"},
				{"Check if Power of Two", "https://leetcode.com/problems/power-of-two/", "Easy"},
				{"Count Number of Set Bits", "https://leetcode.com/problems/counting-bits/", "Easy"},
				{"Set the Rightmost Unset Bit", "https://www.geeksforgeeks.org/set-the-rightmost-unset-bit/", "Easy"},
				{"Swap Two Numbers", "https://www.geeksforgeeks.org/swap-two-numbers-without-using-temporary-variable/", "Easy"},
				{"Divide Two Integers", "https://leetcode.com/problems/divide-two-integers/", "Medium"},
				{"Single Number", "https://leetcode.com/problems/single-number/", "Easy"},
				{"Single Number II", "https://leetcode.com/problems/single-number-ii/", "Medium"},
				{"XOR of Numbers in Range", "https://www.geeksforgeeks.org/find-xor-of-numbers-from-the-range-l-r/", "Easy"},
			}},
			{Name: "Stack & Queue - Basics", Problems: []problemData{
				{"Implement Stack using Arrays", "https://www.geeksforgeeks.org/stack-data-structure-introduction-program/", "Easy"},
				{"Implement Queue using Arrays", "https://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/", "Easy"},
				{"Implement Stack using Queue", "https://leetcode.com/problems/implement-stack-using-queues/", "Easy"},
				{"Implement Queue using Stack", "https://leetcode.com/problems/implement-queue-using-stacks/", "Easy"},
				{"Valid Parentheses", "https://leetcode.com/problems/valid-parentheses/", "Easy"},
				{"Min Stack", "https://leetcode.com/problems/min-stack/", "Medium"},
			}},
			{Name: "Stack & Queue - Problems", Problems: []problemData{
				{"Next Greater Element", "https://leetcode.com/problems/next-greater-element-i/", "Easy"},
				{"Next Greater Element II", "https://leetcode.com/problems/next-greater-element-ii/", "Medium"},
				{"Next Smaller Element", "https://www.geeksforgeeks.org/next-smaller-element/", "Easy"},
				{"Trapping Rain Water", "https://leetcode.com/problems/trapping-rain-water/", "Hard"},
				{"Sum of Subarray Minimums", "https://leetcode.com/problems/sum-of-subarray-minimums/", "Medium"},
				{"Stock Span Problem", "https://leetcode.com/problems/online-stock-span/", "Medium"},
				{"Largest Rectangle in Histogram", "https://leetcode.com/problems/largest-rectangle-in-histogram/", "Hard"},
				{"Sliding Window Maximum", "https://leetcode.com/problems/sliding-window-maximum/", "Hard"},
				{"LRU Cache", "https://leetcode.com/problems/lru-cache/", "Medium"},
				{"LFU Cache", "https://leetcode.com/problems/lfu-cache/", "Hard"},
			}},
			{Name: "Sliding Window & Two Pointer", Problems: []problemData{
				{"Longest Substring Without Repeating Characters", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "Medium"},
				{"Max Consecutive Ones III", "https://leetcode.com/problems/max-consecutive-ones-iii/", "Medium"},
				{"Fruit Into Baskets", "https://leetcode.com/problems/fruit-into-baskets/", "Medium"},
				{"Longest Repeating Character Replacement", "https://leetcode.com/problems/longest-repeating-character-replacement/", "Medium"},
				{"Binary Subarrays With Sum", "https://leetcode.com/problems/binary-subarrays-with-sum/", "Medium"},
				{"Count Nice Subarrays", "https://leetcode.com/problems/count-number-of-nice-subarrays/", "Medium"},
				{"Minimum Window Substring", "https://leetcode.com/problems/minimum-window-substring/", "Hard"},
			}},
			{Name: "Heaps / Priority Queue", Problems: []problemData{
				{"Kth Largest Element", "https://leetcode.com/problems/kth-largest-element-in-an-array/", "Medium"},
				{"Kth Smallest Element", "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/", "Medium"},
				{"Sort K Sorted Array", "https://www.geeksforgeeks.org/nearly-sorted-algorithm/", "Medium"},
				{"Top K Frequent Elements", "https://leetcode.com/problems/top-k-frequent-elements/", "Medium"},
				{"Find Median from Data Stream", "https://leetcode.com/problems/find-median-from-data-stream/", "Hard"},
				{"Merge K Sorted Lists", "https://leetcode.com/problems/merge-k-sorted-lists/", "Hard"},
				{"Task Scheduler", "https://leetcode.com/problems/task-scheduler/", "Medium"},
				{"Hand of Straights", "https://leetcode.com/problems/hand-of-straights/", "Medium"},
			}},
			{Name: "Greedy Algorithms", Problems: []problemData{
				{"Assign Cookies", "https://leetcode.com/problems/assign-cookies/", "Easy"},
				{"Fractional Knapsack", "https://www.geeksforgeeks.org/fractional-knapsack-problem/", "Medium"},
				{"Minimum Coins", "https://leetcode.com/problems/coin-change/", "Medium"},
				{"Lemonade Change", "https://leetcode.com/problems/lemonade-change/", "Easy"},
				{"Valid Parenthesis String", "https://leetcode.com/problems/valid-parenthesis-string/", "Medium"},
				{"N Meetings in One Room", "https://www.geeksforgeeks.org/find-maximum-meetings-in-one-room/", "Easy"},
				{"Jump Game", "https://leetcode.com/problems/jump-game/", "Medium"},
				{"Jump Game II", "https://leetcode.com/problems/jump-game-ii/", "Medium"},
				{"Minimum Platforms", "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/", "Medium"},
				{"Job Sequencing Problem", "https://www.geeksforgeeks.org/job-sequencing-problem/", "Medium"},
			}},
			{Name: "Binary Trees - Traversals", Problems: []problemData{
				{"Inorder Traversal", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Easy"},
				{"Preorder Traversal", "https://leetcode.com/problems/binary-tree-preorder-traversal/", "Easy"},
				{"Postorder Traversal", "https://leetcode.com/problems/binary-tree-postorder-traversal/", "Easy"},
				{"Level Order Traversal", "https://leetcode.com/problems/binary-tree-level-order-traversal/", "Medium"},
				{"Maximum Depth", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "Easy"},
				{"Balanced Binary Tree", "https://leetcode.com/problems/balanced-binary-tree/", "Easy"},
				{"Diameter of Binary Tree", "https://leetcode.com/problems/diameter-of-binary-tree/", "Easy"},
				{"Binary Tree Maximum Path Sum", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "Hard"},
				{"Same Tree", "https://leetcode.com/problems/same-tree/", "Easy"},
				{"Zig Zag Traversal", "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "Medium"},
				{"Boundary Traversal", "https://www.geeksforgeeks.org/boundary-traversal-of-binary-tree/", "Medium"},
				{"Vertical Order Traversal", "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", "Hard"},
				{"Top View of Binary Tree", "https://www.geeksforgeeks.org/print-nodes-top-view-binary-tree/", "Medium"},
				{"Bottom View of Binary Tree", "https://www.geeksforgeeks.org/bottom-view-binary-tree/", "Medium"},
				{"Right/Left View of Binary Tree", "https://leetcode.com/problems/binary-tree-right-side-view/", "Medium"},
				{"Symmetric Binary Tree", "https://leetcode.com/problems/symmetric-tree/", "Easy"},
			}},
			{Name: "Binary Trees - Medium Problems", Problems: []problemData{
				{"LCA of Binary Tree", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "Medium"},
				{"Maximum Width of Binary Tree", "https://leetcode.com/problems/maximum-width-of-binary-tree/", "Medium"},
				{"Children Sum Property", "https://www.geeksforgeeks.org/check-for-children-sum-property-in-a-binary-tree/", "Medium"},
				{"All Nodes at Distance K", "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", "Medium"},
				{"Count Nodes in Complete Binary Tree", "https://leetcode.com/problems/count-complete-tree-nodes/", "Medium"},
				{"Construct BT from Preorder and Inorder", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", "Medium"},
				{"Construct BT from Inorder and Postorder", "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", "Medium"},
				{"Serialize and Deserialize BT", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "Hard"},
				{"Flatten Binary Tree to Linked List", "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", "Medium"},
			}},
			{Name: "Binary Search Trees", Problems: []problemData{
				{"Search in a BST", "https://leetcode.com/problems/search-in-a-binary-search-tree/", "Easy"},
				{"Ceil in BST", "https://www.geeksforgeeks.org/ceil-in-binary-search-tree-bst/", "Easy"},
				{"Floor in BST", "https://www.geeksforgeeks.org/floor-in-binary-search-tree-bst/", "Easy"},
				{"Insert into BST", "https://leetcode.com/problems/insert-into-a-binary-search-tree/", "Medium"},
				{"Delete Node in BST", "https://leetcode.com/problems/delete-node-in-a-bst/", "Medium"},
				{"Kth Smallest in BST", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "Medium"},
				{"Validate BST", "https://leetcode.com/problems/validate-binary-search-tree/", "Medium"},
				{"LCA of BST", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", "Medium"},
				{"Construct BST from Preorder", "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", "Medium"},
				{"Inorder Successor in BST", "https://www.geeksforgeeks.org/inorder-successor-in-binary-search-tree/", "Medium"},
				{"BST Iterator", "https://leetcode.com/problems/binary-search-tree-iterator/", "Medium"},
				{"Two Sum in BST", "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/", "Easy"},
				{"Largest BST in Binary Tree", "https://www.geeksforgeeks.org/largest-bst-binary-tree/", "Medium"},
			}},
			{Name: "Graphs - BFS/DFS", Problems: []problemData{
				{"Number of Islands", "https://leetcode.com/problems/number-of-islands/", "Medium"},
				{"Flood Fill", "https://leetcode.com/problems/flood-fill/", "Easy"},
				{"Rotten Oranges", "https://leetcode.com/problems/rotting-oranges/", "Medium"},
				{"Detect Cycle in Undirected Graph", "https://www.geeksforgeeks.org/detect-cycle-undirected-graph/", "Medium"},
				{"Detect Cycle in Directed Graph", "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/", "Medium"},
				{"01 Matrix", "https://leetcode.com/problems/01-matrix/", "Medium"},
				{"Surrounded Regions", "https://leetcode.com/problems/surrounded-regions/", "Medium"},
				{"Number of Enclaves", "https://leetcode.com/problems/number-of-enclaves/", "Medium"},
				{"Word Ladder", "https://leetcode.com/problems/word-ladder/", "Hard"},
				{"Bipartite Graph", "https://leetcode.com/problems/is-graph-bipartite/", "Medium"},
				{"Topological Sort (DFS)", "https://www.geeksforgeeks.org/topological-sorting/", "Medium"},
				{"Topological Sort (BFS - Kahn's)", "https://www.geeksforgeeks.org/topological-sorting-indegree-based-approach/", "Medium"},
				{"Course Schedule I", "https://leetcode.com/problems/course-schedule/", "Medium"},
				{"Course Schedule II", "https://leetcode.com/problems/course-schedule-ii/", "Medium"},
			}},
			{Name: "Graphs - Shortest Path", Problems: []problemData{
				{"Dijkstra's Algorithm", "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/", "Medium"},
				{"Bellman Ford", "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/", "Medium"},
				{"Floyd Warshall", "https://www.geeksforgeeks.org/floyd-warshall-algorithm-dp-16/", "Medium"},
				{"City With Smallest Number of Neighbors", "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/", "Medium"},
			}},
			{Name: "Graphs - MST & Advanced", Problems: []problemData{
				{"Prim's Algorithm (MST)", "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/", "Medium"},
				{"Kruskal's Algorithm (MST)", "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/", "Medium"},
				{"Number of Operations to Make Network Connected", "https://leetcode.com/problems/number-of-operations-to-make-network-connected/", "Medium"},
				{"Strongly Connected Components (Kosaraju)", "https://www.geeksforgeeks.org/strongly-connected-components/", "Hard"},
				{"Bridges in Graph", "https://www.geeksforgeeks.org/bridge-in-a-graph/", "Hard"},
				{"Articulation Points", "https://www.geeksforgeeks.org/articulation-points-or-cut-vertices-in-a-graph/", "Hard"},
			}},
			{Name: "Dynamic Programming - 1D", Problems: []problemData{
				{"Climbing Stairs", "https://leetcode.com/problems/climbing-stairs/", "Easy"},
				{"Frog Jump", "https://www.geeksforgeeks.org/minimum-cost-to-reach-the-top-of-the-floor-by-climbing-stairs/", "Easy"},
				{"House Robber", "https://leetcode.com/problems/house-robber/", "Medium"},
				{"House Robber II", "https://leetcode.com/problems/house-robber-ii/", "Medium"},
			}},
			{Name: "Dynamic Programming - 2D/Grid", Problems: []problemData{
				{"Unique Paths", "https://leetcode.com/problems/unique-paths/", "Medium"},
				{"Unique Paths II", "https://leetcode.com/problems/unique-paths-ii/", "Medium"},
				{"Minimum Path Sum", "https://leetcode.com/problems/minimum-path-sum/", "Medium"},
				{"Triangle", "https://leetcode.com/problems/triangle/", "Medium"},
				{"Minimum Falling Path Sum", "https://leetcode.com/problems/minimum-falling-path-sum/", "Medium"},
			}},
			{Name: "DP on Subsequences", Problems: []problemData{
				{"Subset Sum Problem", "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/", "Medium"},
				{"Partition Equal Subset Sum", "https://leetcode.com/problems/partition-equal-subset-sum/", "Medium"},
				{"Coin Change", "https://leetcode.com/problems/coin-change/", "Medium"},
				{"Coin Change II", "https://leetcode.com/problems/coin-change-ii/", "Medium"},
				{"Target Sum", "https://leetcode.com/problems/target-sum/", "Medium"},
				{"0-1 Knapsack", "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/", "Medium"},
				{"Unbounded Knapsack", "https://www.geeksforgeeks.org/unbounded-knapsack-repetition-items-allowed/", "Medium"},
				{"Rod Cutting", "https://www.geeksforgeeks.org/cutting-a-rod-dp-13/", "Medium"},
			}},
			{Name: "DP on Strings", Problems: []problemData{
				{"Longest Common Subsequence", "https://leetcode.com/problems/longest-common-subsequence/", "Medium"},
				{"Longest Palindromic Subsequence", "https://leetcode.com/problems/longest-palindromic-subsequence/", "Medium"},
				{"Minimum Insertions to Make Palindrome", "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/", "Hard"},
				{"Edit Distance", "https://leetcode.com/problems/edit-distance/", "Hard"},
				{"Wildcard Matching", "https://leetcode.com/problems/wildcard-matching/", "Hard"},
				{"Distinct Subsequences", "https://leetcode.com/problems/distinct-subsequences/", "Hard"},
			}},
			{Name: "DP on LIS & Stocks", Problems: []problemData{
				{"Longest Increasing Subsequence", "https://leetcode.com/problems/longest-increasing-subsequence/", "Medium"},
				{"Longest String Chain", "https://leetcode.com/problems/longest-string-chain/", "Medium"},
				{"Largest Divisible Subset", "https://leetcode.com/problems/largest-divisible-subset/", "Medium"},
				{"Best Time to Buy and Sell Stock", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Easy"},
				{"Buy and Sell Stock II", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/", "Medium"},
				{"Buy and Sell Stock III", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/", "Hard"},
				{"Buy and Sell Stock IV", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", "Hard"},
				{"Buy and Sell Stock with Cooldown", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/", "Medium"},
			}},
			{Name: "DP - MCM & Partition", Problems: []problemData{
				{"Matrix Chain Multiplication", "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/", "Hard"},
				{"Minimum Cost to Cut a Stick", "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", "Hard"},
				{"Burst Balloons", "https://leetcode.com/problems/burst-balloons/", "Hard"},
				{"Palindrome Partitioning II", "https://leetcode.com/problems/palindrome-partitioning-ii/", "Hard"},
				{"Partition Array for Maximum Sum", "https://leetcode.com/problems/partition-array-for-maximum-sum/", "Medium"},
			}},
			{Name: "Trie", Problems: []problemData{
				{"Implement Trie", "https://leetcode.com/problems/implement-trie-prefix-tree/", "Medium"},
				{"Implement Trie II", "https://leetcode.com/problems/implement-trie-ii-prefix-tree/", "Medium"},
				{"Longest String with All Prefixes", "https://leetcode.com/problems/longest-word-in-dictionary/", "Medium"},
				{"Number of Distinct Substrings", "https://www.geeksforgeeks.org/count-number-of-distinct-substring-in-a-string/", "Hard"},
				{"Maximum XOR of Two Numbers", "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", "Medium"},
				{"Maximum XOR With Element From Array", "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/", "Hard"},
			}},
		},
	}
}
