package database

func sdeSheet() sheetData {
	return sheetData{
		Name:        "SDE Sheet",
		Slug:        "sde-sheet",
		Description: "Most Frequently Asked Interview Questions",
		Topics: []topicData{
			{Name: "Arrays", Problems: []problemData{
				{"Set Matrix Zeroes", "https://leetcode.com/problems/set-matrix-zeroes/", "Medium"},
				{"Pascal's Triangle", "https://leetcode.com/problems/pascals-triangle/", "Easy"},
				{"Next Permutation", "https://leetcode.com/problems/next-permutation/", "Medium"},
				{"Kadane's Algorithm", "https://leetcode.com/problems/maximum-subarray/", "Medium"},
				{"Sort an array of 0's 1's and 2's", "https://leetcode.com/problems/sort-colors/", "Medium"},
				{"Stock Buy and Sell", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Easy"},
			}},
			{Name: "Arrays Part-II", Problems: []problemData{
				{"Rotate Matrix", "https://leetcode.com/problems/rotate-image/", "Medium"},
				{"Merge Overlapping Subintervals", "https://leetcode.com/problems/merge-intervals/", "Medium"},
				{"Merge two sorted arrays without extra space", "https://leetcode.com/problems/merge-sorted-array/", "Easy"},
				{"Find the Duplicate Number", "https://leetcode.com/problems/find-the-duplicate-number/", "Medium"},
				{"Find the repeating and missing number", "https://www.geeksforgeeks.org/find-a-repeating-and-a-missing-number/", "Medium"},
				{"Inversion of Array (Merge Sort)", "https://www.geeksforgeeks.org/counting-inversions/", "Hard"},
			}},
			{Name: "Arrays Part-III", Problems: []problemData{
				{"Search in a 2D matrix", "https://leetcode.com/problems/search-a-2d-matrix/", "Medium"},
				{"Pow(x, n)", "https://leetcode.com/problems/powx-n/", "Medium"},
				{"Majority Element (>N/2 times)", "https://leetcode.com/problems/majority-element/", "Easy"},
				{"Majority Element (>N/3 times)", "https://leetcode.com/problems/majority-element-ii/", "Medium"},
				{"Grid Unique Paths", "https://leetcode.com/problems/unique-paths/", "Medium"},
				{"Reverse Pairs", "https://leetcode.com/problems/reverse-pairs/", "Hard"},
			}},
			{Name: "Arrays Part-IV", Problems: []problemData{
				{"Two Sum", "https://leetcode.com/problems/two-sum/", "Easy"},
				{"4 Sum", "https://leetcode.com/problems/4sum/", "Medium"},
				{"Longest Consecutive Sequence", "https://leetcode.com/problems/longest-consecutive-sequence/", "Medium"},
				{"Largest Subarray with K Sum", "https://www.geeksforgeeks.org/largest-subarray-with-equal-number-of-0s-and-1s/", "Medium"},
				{"Count subarrays with given xor K", "https://www.geeksforgeeks.org/count-number-subarrays-given-xor/", "Medium"},
				{"Longest Substring Without Repeating Characters", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "Medium"},
			}},
			{Name: "Linked List", Problems: []problemData{
				{"Reverse a Linked List", "https://leetcode.com/problems/reverse-linked-list/", "Easy"},
				{"Find Middle of Linked List", "https://leetcode.com/problems/middle-of-the-linked-list/", "Easy"},
				{"Merge two Sorted Lists", "https://leetcode.com/problems/merge-two-sorted-lists/", "Easy"},
				{"Remove Nth node from back of LL", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "Medium"},
				{"Add two numbers as Linked List", "https://leetcode.com/problems/add-two-numbers/", "Medium"},
				{"Delete Node in a Linked List", "https://leetcode.com/problems/delete-node-in-a-linked-list/", "Medium"},
			}},
			{Name: "Linked List Part-II", Problems: []problemData{
				{"Find intersection point of Y LL", "https://leetcode.com/problems/intersection-of-two-linked-lists/", "Easy"},
				{"Detect a cycle in Linked List", "https://leetcode.com/problems/linked-list-cycle/", "Easy"},
				{"Reverse LL in groups of size K", "https://leetcode.com/problems/reverse-nodes-in-k-group/", "Hard"},
				{"Check if LL is palindrome or not", "https://leetcode.com/problems/palindrome-linked-list/", "Easy"},
				{"Find the starting point of the Loop", "https://leetcode.com/problems/linked-list-cycle-ii/", "Medium"},
				{"Flattening of a Linked List", "https://www.geeksforgeeks.org/flattening-a-linked-list/", "Medium"},
			}},
			{Name: "Linked List and Arrays", Problems: []problemData{
				{"Rotate a Linked List", "https://leetcode.com/problems/rotate-list/", "Medium"},
				{"Clone a Linked List with random and next pointer", "https://leetcode.com/problems/copy-list-with-random-pointer/", "Medium"},
				{"3 Sum", "https://leetcode.com/problems/3sum/", "Medium"},
				{"Trapping Rainwater", "https://leetcode.com/problems/trapping-rain-water/", "Hard"},
				{"Remove duplicates from sorted array", "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", "Easy"},
				{"Maximum Consecutive Ones", "https://leetcode.com/problems/max-consecutive-ones/", "Easy"},
			}},
			{Name: "Greedy Algorithm", Problems: []problemData{
				{"N meetings in one room", "https://www.geeksforgeeks.org/find-maximum-meetings-in-one-room/", "Easy"},
				{"Minimum number of platforms", "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/", "Medium"},
				{"Job Sequencing Problem", "https://www.geeksforgeeks.org/job-sequencing-problem/", "Medium"},
				{"Fractional Knapsack", "https://www.geeksforgeeks.org/fractional-knapsack-problem/", "Medium"},
				{"Minimum coins", "https://leetcode.com/problems/coin-change/", "Medium"},
				{"Assign Cookies", "https://leetcode.com/problems/assign-cookies/", "Easy"},
			}},
			{Name: "Recursion", Problems: []problemData{
				{"Subset Sums", "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/", "Medium"},
				{"Subsets II", "https://leetcode.com/problems/subsets-ii/", "Medium"},
				{"Combination Sum", "https://leetcode.com/problems/combination-sum/", "Medium"},
				{"Combination Sum II", "https://leetcode.com/problems/combination-sum-ii/", "Medium"},
				{"Palindrome Partitioning", "https://leetcode.com/problems/palindrome-partitioning/", "Medium"},
				{"Permutation Sequence", "https://leetcode.com/problems/permutation-sequence/", "Hard"},
			}},
			{Name: "Recursion and Backtracking", Problems: []problemData{
				{"Permutations of a String", "https://leetcode.com/problems/permutations/", "Medium"},
				{"N Queen Problem", "https://leetcode.com/problems/n-queens/", "Hard"},
				{"Sudoku Solver", "https://leetcode.com/problems/sudoku-solver/", "Hard"},
				{"M Coloring Problem", "https://www.geeksforgeeks.org/m-coloring-problem-backtracking-5/", "Medium"},
				{"Rat in a Maze", "https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-2/", "Medium"},
				{"Word Break", "https://leetcode.com/problems/word-break/", "Medium"},
			}},
			{Name: "Binary Search", Problems: []problemData{
				{"N-th root of an integer", "https://www.geeksforgeeks.org/n-th-root-number/", "Easy"},
				{"Matrix Median", "https://www.geeksforgeeks.org/find-median-row-wise-sorted-matrix/", "Hard"},
				{"Single element in sorted array", "https://leetcode.com/problems/single-element-in-a-sorted-array/", "Medium"},
				{"Search in rotated sorted array", "https://leetcode.com/problems/search-in-rotated-sorted-array/", "Medium"},
				{"Median of 2 sorted arrays", "https://leetcode.com/problems/median-of-two-sorted-arrays/", "Hard"},
				{"K-th element of 2 sorted arrays", "https://www.geeksforgeeks.org/k-th-element-two-sorted-arrays/", "Medium"},
				{"Allocate Minimum Number of Pages", "https://www.geeksforgeeks.org/allocate-minimum-number-pages/", "Hard"},
				{"Aggressive Cows", "https://www.spoj.com/problems/AGGRCOW/", "Hard"},
			}},
			{Name: "Heaps", Problems: []problemData{
				{"Implement Max Heap", "https://www.geeksforgeeks.org/max-heap-in-java/", "Easy"},
				{"Kth Largest Element", "https://leetcode.com/problems/kth-largest-element-in-an-array/", "Medium"},
				{"Maximum Sum Combination", "https://www.geeksforgeeks.org/k-maximum-sum-combinations-two-arrays/", "Medium"},
				{"Find Median from Data Stream", "https://leetcode.com/problems/find-median-from-data-stream/", "Hard"},
				{"Merge K Sorted Lists", "https://leetcode.com/problems/merge-k-sorted-lists/", "Hard"},
				{"Top K Frequent Elements", "https://leetcode.com/problems/top-k-frequent-elements/", "Medium"},
			}},
			{Name: "Stack and Queue", Problems: []problemData{
				{"Implement Stack using Arrays", "https://www.geeksforgeeks.org/stack-data-structure-introduction-program/", "Easy"},
				{"Implement Queue using Arrays", "https://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/", "Easy"},
				{"Implement Stack using Queue", "https://leetcode.com/problems/implement-stack-using-queues/", "Easy"},
				{"Implement Queue using Stack", "https://leetcode.com/problems/implement-queue-using-stacks/", "Easy"},
				{"Balanced Parentheses", "https://leetcode.com/problems/valid-parentheses/", "Easy"},
				{"Next Greater Element", "https://leetcode.com/problems/next-greater-element-i/", "Easy"},
				{"Sort a Stack", "https://www.geeksforgeeks.org/sort-a-stack-using-recursion/", "Medium"},
			}},
			{Name: "Stack and Queue Part-II", Problems: []problemData{
				{"Next Smaller Element", "https://www.geeksforgeeks.org/next-smaller-element/", "Easy"},
				{"LRU Cache", "https://leetcode.com/problems/lru-cache/", "Medium"},
				{"LFU Cache", "https://leetcode.com/problems/lfu-cache/", "Hard"},
				{"Largest Rectangle in Histogram", "https://leetcode.com/problems/largest-rectangle-in-histogram/", "Hard"},
				{"Sliding Window Maximum", "https://leetcode.com/problems/sliding-window-maximum/", "Hard"},
				{"Implement Min Stack", "https://leetcode.com/problems/min-stack/", "Medium"},
				{"Rotten Oranges", "https://leetcode.com/problems/rotting-oranges/", "Medium"},
				{"Stock Span Problem", "https://leetcode.com/problems/online-stock-span/", "Medium"},
				{"Maximum of Minimums of every window size", "https://www.geeksforgeeks.org/find-the-maximum-of-minimums-for-every-window-size-in-a-given-array/", "Hard"},
				{"The Celebrity Problem", "https://leetcode.com/problems/find-the-celebrity/", "Medium"},
			}},
			{Name: "String", Problems: []problemData{
				{"Reverse Words in a String", "https://leetcode.com/problems/reverse-words-in-a-string/", "Medium"},
				{"Longest Palindromic Substring", "https://leetcode.com/problems/longest-palindromic-substring/", "Medium"},
				{"Roman Number to Integer", "https://leetcode.com/problems/roman-to-integer/", "Easy"},
				{"Implement ATOI/STRSTR", "https://leetcode.com/problems/string-to-integer-atoi/", "Medium"},
				{"Longest Common Prefix", "https://leetcode.com/problems/longest-common-prefix/", "Easy"},
				{"Rabin Karp Algorithm", "https://leetcode.com/problems/repeated-string-match/", "Medium"},
			}},
			{Name: "String Part-II", Problems: []problemData{
				{"Z Function", "https://leetcode.com/problems/implement-strstr/", "Medium"},
				{"KMP Algorithm / LPS Array", "https://leetcode.com/problems/implement-strstr/", "Medium"},
				{"Minimum characters to make string palindrome", "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/", "Hard"},
				{"Valid Anagram", "https://leetcode.com/problems/valid-anagram/", "Easy"},
				{"Count and Say", "https://leetcode.com/problems/count-and-say/", "Medium"},
				{"Compare Version Numbers", "https://leetcode.com/problems/compare-version-numbers/", "Medium"},
			}},
			{Name: "Binary Tree", Problems: []problemData{
				{"Inorder Traversal", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Easy"},
				{"Preorder Traversal", "https://leetcode.com/problems/binary-tree-preorder-traversal/", "Easy"},
				{"Postorder Traversal", "https://leetcode.com/problems/binary-tree-postorder-traversal/", "Easy"},
				{"Morris Inorder Traversal", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Medium"},
				{"Morris Preorder Traversal", "https://leetcode.com/problems/binary-tree-preorder-traversal/", "Medium"},
				{"Left/Right View of Binary Tree", "https://leetcode.com/problems/binary-tree-right-side-view/", "Medium"},
				{"Bottom View of Binary Tree", "https://www.geeksforgeeks.org/bottom-view-binary-tree/", "Medium"},
				{"Top View of Binary Tree", "https://www.geeksforgeeks.org/print-nodes-top-view-binary-tree/", "Medium"},
				{"Pre Post Inorder in one traversal", "https://www.geeksforgeeks.org/preorder-postorder-inorder-traversal-of-binary-tree-using-single-stack/", "Medium"},
				{"Vertical Order Traversal", "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", "Hard"},
				{"Root to Node Path", "https://www.geeksforgeeks.org/print-path-root-given-node-binary-tree/", "Medium"},
				{"Maximum Width of Binary Tree", "https://leetcode.com/problems/maximum-width-of-binary-tree/", "Medium"},
			}},
			{Name: "Binary Tree Part-II", Problems: []problemData{
				{"Level Order Traversal", "https://leetcode.com/problems/binary-tree-level-order-traversal/", "Medium"},
				{"Maximum Depth of Binary Tree", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "Easy"},
				{"Diameter of Binary Tree", "https://leetcode.com/problems/diameter-of-binary-tree/", "Easy"},
				{"Check for Balanced Binary Tree", "https://leetcode.com/problems/balanced-binary-tree/", "Easy"},
				{"LCA in Binary Tree", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "Medium"},
				{"Check if two trees are identical", "https://leetcode.com/problems/same-tree/", "Easy"},
				{"Zig Zag Traversal", "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "Medium"},
				{"Boundary Traversal", "https://www.geeksforgeeks.org/boundary-traversal-of-binary-tree/", "Medium"},
			}},
			{Name: "Binary Tree Part-III", Problems: []problemData{
				{"Maximum Path Sum", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "Hard"},
				{"Construct BT from Preorder and Inorder", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", "Medium"},
				{"Construct BT from Inorder and Postorder", "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", "Medium"},
				{"Symmetric Binary Tree", "https://leetcode.com/problems/symmetric-tree/", "Easy"},
				{"Flatten Binary Tree to Linked List", "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", "Medium"},
				{"Children Sum Property", "https://www.geeksforgeeks.org/check-for-children-sum-property-in-a-binary-tree/", "Medium"},
			}},
			{Name: "Binary Search Tree", Problems: []problemData{
				{"Populating Next Right Pointers", "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/", "Medium"},
				{"Search in a BST", "https://leetcode.com/problems/search-in-a-binary-search-tree/", "Easy"},
				{"Construct BST from given keys", "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", "Easy"},
				{"Construct BST from preorder", "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", "Medium"},
				{"Check if a tree is a BST", "https://leetcode.com/problems/validate-binary-search-tree/", "Medium"},
				{"LCA in BST", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", "Medium"},
				{"Inorder Successor/Predecessor in BST", "https://www.geeksforgeeks.org/inorder-successor-in-binary-search-tree/", "Medium"},
			}},
			{Name: "Binary Search Tree Part-II", Problems: []problemData{
				{"Floor in a BST", "https://www.geeksforgeeks.org/floor-in-binary-search-tree-bst/", "Easy"},
				{"Ceil in a BST", "https://www.geeksforgeeks.org/ceil-in-binary-search-tree-bst/", "Easy"},
				{"Kth Smallest element in BST", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "Medium"},
				{"Kth Largest element in BST", "https://www.geeksforgeeks.org/kth-largest-element-in-bst-when-modification-to-bst-is-not-allowed/", "Medium"},
				{"Two Sum in BST", "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/", "Easy"},
				{"BST Iterator", "https://leetcode.com/problems/binary-search-tree-iterator/", "Medium"},
				{"Largest BST in Binary Tree", "https://www.geeksforgeeks.org/largest-bst-binary-tree/", "Medium"},
				{"Serialize and Deserialize Binary Tree", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "Hard"},
			}},
			{Name: "Binary Trees Miscellaneous", Problems: []problemData{
				{"Binary Tree to Doubly Linked List", "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", "Medium"},
				{"Find Median in a Data Stream", "https://leetcode.com/problems/find-median-from-data-stream/", "Hard"},
				{"Kth Largest element in a stream", "https://leetcode.com/problems/kth-largest-element-in-a-stream/", "Easy"},
				{"Distinct Numbers in Window", "https://www.geeksforgeeks.org/count-distinct-elements-in-every-window-of-size-k/", "Medium"},
				{"Count nodes in Complete Binary Tree", "https://leetcode.com/problems/count-complete-tree-nodes/", "Medium"},
			}},
			{Name: "Graph", Problems: []problemData{
				{"Clone a Graph", "https://leetcode.com/problems/clone-graph/", "Medium"},
				{"DFS", "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/", "Easy"},
				{"BFS", "https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/", "Easy"},
				{"Detect Cycle in Undirected Graph", "https://leetcode.com/problems/course-schedule/", "Medium"},
				{"Detect Cycle in Directed Graph", "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/", "Medium"},
				{"Topological Sort (BFS - Kahn's)", "https://www.geeksforgeeks.org/topological-sorting-indegree-based-approach/", "Medium"},
				{"Topological Sort (DFS)", "https://www.geeksforgeeks.org/topological-sorting/", "Medium"},
				{"Number of Islands", "https://leetcode.com/problems/number-of-islands/", "Medium"},
				{"Bipartite Check", "https://leetcode.com/problems/is-graph-bipartite/", "Medium"},
			}},
			{Name: "Graph Part-II", Problems: []problemData{
				{"Strongly Connected Components (Kosaraju)", "https://www.geeksforgeeks.org/strongly-connected-components/", "Hard"},
				{"Dijkstra's Algorithm", "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/", "Medium"},
				{"Bellman Ford Algorithm", "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/", "Medium"},
				{"Floyd Warshall Algorithm", "https://www.geeksforgeeks.org/floyd-warshall-algorithm-dp-16/", "Medium"},
				{"MST using Prim's Algorithm", "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/", "Medium"},
				{"MST using Kruskal's Algorithm", "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/", "Medium"},
			}},
			{Name: "Dynamic Programming", Problems: []problemData{
				{"Max Product Subarray", "https://leetcode.com/problems/maximum-product-subarray/", "Medium"},
				{"Longest Increasing Subsequence", "https://leetcode.com/problems/longest-increasing-subsequence/", "Medium"},
				{"Longest Common Subsequence", "https://leetcode.com/problems/longest-common-subsequence/", "Medium"},
				{"0-1 Knapsack", "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/", "Medium"},
				{"Edit Distance", "https://leetcode.com/problems/edit-distance/", "Hard"},
				{"Maximum Sum Increasing Subsequence", "https://www.geeksforgeeks.org/maximum-sum-increasing-subsequence-dp-14/", "Medium"},
				{"Matrix Chain Multiplication", "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/", "Hard"},
			}},
			{Name: "Dynamic Programming Part-II", Problems: []problemData{
				{"Minimum Path Sum", "https://leetcode.com/problems/minimum-path-sum/", "Medium"},
				{"Coin Change", "https://leetcode.com/problems/coin-change/", "Medium"},
				{"Subset Sum", "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/", "Medium"},
				{"Rod Cutting", "https://www.geeksforgeeks.org/cutting-a-rod-dp-13/", "Medium"},
				{"Egg Dropping", "https://leetcode.com/problems/super-egg-drop/", "Hard"},
				{"Word Break", "https://leetcode.com/problems/word-break/", "Medium"},
				{"Palindrome Partitioning (DP)", "https://leetcode.com/problems/palindrome-partitioning-ii/", "Hard"},
			}},
			{Name: "Trie", Problems: []problemData{
				{"Implement Trie (Prefix Tree)", "https://leetcode.com/problems/implement-trie-prefix-tree/", "Medium"},
				{"Implement Trie II", "https://leetcode.com/problems/implement-trie-ii-prefix-tree/", "Medium"},
				{"Longest String with All Prefixes", "https://leetcode.com/problems/longest-word-in-dictionary/", "Medium"},
				{"Number of Distinct Substrings", "https://www.geeksforgeeks.org/count-number-of-distinct-substring-in-a-string/", "Hard"},
				{"Power Set", "https://leetcode.com/problems/subsets/", "Medium"},
				{"Maximum XOR of Two Numbers", "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", "Medium"},
			}},
			{Name: "Operating System", Problems: []problemData{
				{"Process vs Thread", "https://www.geeksforgeeks.org/difference-between-process-and-thread/", "Easy"},
				{"Mutex vs Semaphore", "https://www.geeksforgeeks.org/mutex-vs-semaphore/", "Easy"},
				{"CPU Scheduling", "https://www.geeksforgeeks.org/cpu-scheduling-in-operating-systems/", "Medium"},
				{"Deadlock Prevention & Avoidance", "https://www.geeksforgeeks.org/introduction-of-deadlock-in-operating-system/", "Medium"},
				{"Memory Management", "https://www.geeksforgeeks.org/paging-in-operating-system/", "Medium"},
				{"Virtual Memory & Thrashing", "https://www.geeksforgeeks.org/virtual-memory-in-operating-system/", "Medium"},
			}},
			{Name: "DBMS", Problems: []problemData{
				{"ACID Properties", "https://www.geeksforgeeks.org/acid-properties-in-dbms/", "Easy"},
				{"Normalization (1NF, 2NF, 3NF, BCNF)", "https://www.geeksforgeeks.org/normal-forms-in-dbms/", "Medium"},
				{"Indexing and B+ Trees", "https://www.geeksforgeeks.org/indexing-in-databases-set-1/", "Medium"},
				{"Transactions and Concurrency Control", "https://www.geeksforgeeks.org/concurrency-control-in-dbms/", "Medium"},
				{"SQL vs NoSQL", "https://www.geeksforgeeks.org/difference-between-sql-and-nosql/", "Easy"},
				{"Joins in SQL", "https://www.geeksforgeeks.org/sql-join-set-1-inner-left-right-and-full-joins/", "Easy"},
			}},
			{Name: "System Design", Problems: []problemData{
				{"Design TinyURL", "https://www.geeksforgeeks.org/system-design-url-shortening-service/", "Medium"},
				{"Design Twitter", "https://www.geeksforgeeks.org/design-twitter-a-system-design-interview-question/", "Hard"},
				{"Design WhatsApp", "https://www.geeksforgeeks.org/design-whatsapp/", "Hard"},
				{"Load Balancing", "https://www.geeksforgeeks.org/load-balancing-in-system-design/", "Medium"},
				{"Caching", "https://www.geeksforgeeks.org/caching-system-design-concept-for-beginners/", "Medium"},
				{"Database Sharding", "https://www.geeksforgeeks.org/database-sharding-a-system-design-concept/", "Medium"},
			}},
		},
	}
}
