package database

func cpSheet() sheetData {
	return sheetData{
		Name:        "CP Sheet",
		Slug:        "cp-sheet",
		Description: "Competitive Programming Problems",
		Topics: []topicData{
			{Name: "Implementation / Constructive", Problems: []problemData{
				{"Bit++", "https://codeforces.com/problemset/problem/282/A", "Easy"},
				{"Chewbacca and Number", "https://codeforces.com/contest/514/problem/A", "Easy"},
				{"Beautiful Matrix", "https://codeforces.com/problemset/problem/263/A", "Easy"},
				{"Soft Drinking", "https://codeforces.com/problemset/problem/151/A", "Easy"},
				{"Meeting Friends", "https://codeforces.com/problemset/problem/723/A", "Easy"},
				{"Sum of Round Numbers", "https://codeforces.com/problemset/problem/1352/A", "Easy"},
				{"Fox And Snake", "https://codeforces.com/problemset/problem/510/A", "Easy"},
				{"Anton and Polyhedrons", "https://codeforces.com/problemset/problem/785/A", "Easy"},
				{"Arrival of the General", "https://codeforces.com/problemset/problem/144/A", "Easy"},
				{"In Search of an Easy Problem", "https://codeforces.com/problemset/problem/1030/A", "Easy"},
				{"Presents", "https://codeforces.com/problemset/problem/136/A", "Easy"},
				{"Nearly Lucky Number", "https://codeforces.com/problemset/problem/110/A", "Easy"},
				{"Tram", "https://codeforces.com/problemset/problem/116/A", "Easy"},
				{"Wrong Subtraction", "https://codeforces.com/problemset/problem/977/A", "Easy"},
				{"Soldier and Bananas", "https://codeforces.com/problemset/problem/546/A", "Easy"},
				{"Bear and Big Brother", "https://codeforces.com/problemset/problem/791/A", "Easy"},
				{"Boy or Girl", "https://codeforces.com/problemset/problem/236/A", "Easy"},
				{"Word Capitalization", "https://codeforces.com/problemset/problem/281/A", "Easy"},
				{"Helpful Maths", "https://codeforces.com/problemset/problem/339/A", "Easy"},
				{"C+=", "https://codeforces.com/problemset/problem/1368/A", "Easy"},
				{"Maximum Increase", "https://codeforces.com/problemset/problem/702/A", "Easy"},
				{"Gennady and a Card Game", "https://codeforces.com/problemset/problem/1097/A", "Easy"},
				{"Vanya and Cubes", "https://codeforces.com/problemset/problem/492/A", "Easy"},
				{"Boring Apartments", "https://codeforces.com/problemset/problem/1433/A", "Easy"},
				{"Erasing Zeroes", "https://codeforces.com/problemset/problem/1303/A", "Easy"},
				{"Repeating Cipher", "https://codeforces.com/problemset/problem/1095/A", "Easy"},
				{"Fix You", "https://codeforces.com/problemset/problem/1391/B", "Easy"},
				{"String Task", "https://codeforces.com/problemset/problem/118/A", "Easy"},
				{"Assigning to Classes", "https://codeforces.com/problemset/problem/1300/B", "Medium"},
				{"Numbers on Whiteboard", "https://codeforces.com/problemset/problem/1430/C", "Medium"},
				{"Petr and Book", "https://codeforces.com/contest/139/problem/A", "Easy"},
				{"k-String", "https://codeforces.com/problemset/problem/219/A", "Easy"},
				{"Game 23", "https://codeforces.com/problemset/problem/1141/A", "Easy"},
				{"Present from Lena", "https://codeforces.com/problemset/problem/118/B", "Easy"},
				{"Donut Shops", "https://codeforces.com/problemset/problem/1373/A", "Easy"},
				{"Buttons", "https://codeforces.com/problemset/problem/268/B", "Easy"},
				{"Dreamoon and Stairs", "https://codeforces.com/problemset/problem/476/A", "Easy"},
				{"New Year Transportation", "https://codeforces.com/problemset/problem/500/A", "Easy"},
				{"cAPS lOCK", "https://codeforces.com/problemset/problem/131/A", "Easy"},
				{"Chocolates", "https://codeforces.com/problemset/problem/1139/B", "Easy"},
				{"City Day", "https://codeforces.com/problemset/problem/1199/A", "Medium"},
				{"Diverse Substring", "https://codeforces.com/problemset/problem/1073/A", "Easy"},
				{"Lucky Sum of Digits", "https://codeforces.com/problemset/problem/109/A", "Easy"},
				{"Rooms and Staircases", "https://codeforces.com/problemset/problem/1244/B", "Medium"},
				{"Palindromic Twist", "https://codeforces.com/problemset/problem/1027/A", "Easy"},
				{"Shuffle Hashing", "https://codeforces.com/problemset/problem/1278/A", "Easy"},
				{"Middle of the Contest", "https://codeforces.com/problemset/problem/1133/A", "Easy"},
				{"OR in Matrix", "https://codeforces.com/problemset/problem/486/B", "Medium"},
				{"Balanced Rating Changes", "https://codeforces.com/problemset/problem/1237/A", "Easy"},
				{"Amr and Music", "https://codeforces.com/problemset/problem/507/A", "Easy"},
			}},
			{Name: "Maths", Problems: []problemData{
				{"Ichihime and Triangle", "https://codeforces.com/problemset/problem/1337/A", "Easy"},
				{"LCM Problem", "https://codeforces.com/problemset/problem/1389/A", "Easy"},
				{"Mahmoud and Ehab and the even-odd game", "https://codeforces.com/problemset/problem/959/A", "Easy"},
				{"Array with Odd Sum", "https://codeforces.com/problemset/problem/1296/A", "Easy"},
				{"Floor Number", "https://codeforces.com/problemset/problem/1426/A", "Easy"},
				{"Three Pairwise Maximums", "https://codeforces.com/problemset/problem/1385/A", "Easy"},
				{"Park Lighting", "https://codeforces.com/problemset/problem/1358/A", "Easy"},
				{"Collecting Coins", "https://codeforces.com/problemset/problem/1294/A", "Easy"},
				{"Required Remainder", "https://codeforces.com/problemset/problem/1374/A", "Easy"},
				{"Magical Sticks", "https://codeforces.com/problemset/problem/1371/A", "Easy"},
				{"Minimal Square", "https://codeforces.com/problemset/problem/1360/A", "Easy"},
				{"Even Array", "https://codeforces.com/problemset/problem/1367/B", "Easy"},
				{"Most Unstable Array", "https://codeforces.com/problemset/problem/1353/A", "Easy"},
				{"Balanced Array", "https://codeforces.com/problemset/problem/1343/B", "Medium"},
				{"Buy a Shovel", "https://codeforces.com/problemset/problem/732/A", "Easy"},
				{"Restoring Three Numbers", "https://codeforces.com/problemset/problem/1154/A", "Easy"},
				{"Yet Another Two Integers Problem", "https://codeforces.com/problemset/problem/1409/A", "Easy"},
				{"Divisibility Problem", "https://codeforces.com/problemset/problem/1328/A", "Easy"},
				{"Elephant", "https://codeforces.com/problemset/problem/617/A", "Easy"},
				{"Domino Piling", "https://codeforces.com/problemset/problem/50/A", "Easy"},
				{"Emotes", "https://codeforces.com/problemset/problem/1117/B", "Easy"},
				{"Drinks Choosing", "https://codeforces.com/problemset/problem/1195/A", "Easy"},
				{"Chunga-Changa", "https://codeforces.com/problemset/problem/1181/A", "Medium"},
				{"Theatre-Square", "https://codeforces.com/problemset/problem/1/A", "Easy"},
				{"Young Physicist", "https://codeforces.com/problemset/problem/69/A", "Easy"},
				{"Pasha and Stick", "https://codeforces.com/problemset/problem/610/A", "Easy"},
				{"String LCM", "https://codeforces.com/problemset/problem/1473/B", "Medium"},
				{"K-divisible Sum", "https://codeforces.com/problemset/problem/1476/A", "Easy"},
				{"Berland Poker", "https://codeforces.com/problemset/problem/1359/A", "Medium"},
				{"Sequence with Digits", "https://codeforces.com/problemset/problem/1355/A", "Medium"},
			}},
			{Name: "Binary Search", Problems: []problemData{
				{"Hamburgers", "https://codeforces.com/contest/371/problem/C", "Medium"},
				{"Magic Powder - 1", "https://codeforces.com/contest/670/problem/D1", "Medium"},
				{"Pipeline", "https://codeforces.com/contest/287/problem/B", "Medium"},
				{"Poisoned Dagger", "https://codeforces.com/problemset/problem/1613/C", "Medium"},
				{"Mike and Chocolate Thieves", "https://codeforces.com/contest/689/problem/C", "Medium"},
				{"Increasing by Modulo", "https://codeforces.com/contest/1169/problem/C", "Medium"},
				{"Vasya and Robot", "https://codeforces.com/contest/1073/problem/C", "Medium"},
				{"Multiplication Table", "https://codeforces.com/contest/448/problem/D", "Hard"},
				{"Stressful Training", "https://codeforces.com/contest/1132/problem/D", "Hard"},
				{"Water Taps", "https://codeforces.com/contest/954/problem/E", "Hard"},
				{"Minimax Problem", "https://codeforces.com/contest/1288/problem/D", "Hard"},
			}},
			{Name: "Prime, Sieve, Prime Factorisation", Problems: []problemData{
				{"Prime Generator", "https://www.spoj.com/problems/PRIME1/", "Easy"},
				{"Printing some primes", "https://www.spoj.com/problems/TDPRIMES/", "Easy"},
				{"Finding the Kth Prime", "https://www.spoj.com/problems/TDKPRIME/", "Easy"},
				{"Good Sequences", "https://codeforces.com/contest/264/problem/B", "Medium"},
				{"Taxes", "https://codeforces.com/contest/735/problem/D", "Medium"},
				{"Soldier and Number Game", "https://codeforces.com/contest/546/problem/D", "Medium"},
				{"Reducing Fractions", "https://codeforces.com/contest/222/problem/C", "Medium"},
				{"Petya and Divisors", "https://codeforces.com/problemset/problem/111/B", "Medium"},
				{"Primes and Multiplication", "https://codeforces.com/contest/1228/problem/C", "Hard"},
				{"GCD Counting", "https://codeforces.com/contest/1101/problem/D", "Hard"},
			}},
			{Name: "Bit Manipulation / Power Set", Problems: []problemData{
				{"New Year's Eve", "https://codeforces.com/problemset/problem/912/B", "Easy"},
				{"Special Numbers", "https://codeforces.com/problemset/problem/1594/B", "Medium"},
				{"Petr and a Combination Lock", "https://codeforces.com/problemset/problem/1097/B", "Easy"},
				{"Array Elimination", "https://codeforces.com/contest/1602/problem/C", "Medium"},
				{"Powers Of Two", "https://codeforces.com/problemset/problem/1095/C", "Medium"},
				{"Berland Crossword", "https://codeforces.com/problemset/problem/1494/B", "Medium"},
				{"Dima and a Bad XOR", "https://codeforces.com/problemset/problem/1151/B", "Medium"},
				{"p-binary", "https://codeforces.com/problemset/problem/1225/C", "Medium"},
				{"Ehab and the Expected XOR Problem", "https://codeforces.com/contest/1174/problem/D", "Hard"},
				{"505", "https://codeforces.com/problemset/problem/1391/D", "Hard"},
				{"Zookeeper and The Infinite Zoo", "https://codeforces.com/problemset/problem/1491/D", "Hard"},
			}},
			{Name: "Stack / Queues / Priority Queues", Problems: []problemData{
				{"Alternating Current", "https://codeforces.com/contest/343/problem/B", "Medium"},
				{"Cd and pwd commands", "https://codeforces.com/contest/158/problem/C", "Easy"},
				{"Longest Regular Bracket Sequence", "https://codeforces.com/contest/5/problem/C", "Hard"},
				{"Pair of Numbers", "https://codeforces.com/contest/359/problem/D", "Medium"},
				{"Skyscrapers (hard version)", "https://codeforces.com/contest/1313/problem/C2", "Hard"},
				{"Phoenix and Towers", "https://codeforces.com/contest/1515/problem/C", "Medium"},
				{"Psychos in a Line", "https://codeforces.com/contest/319/problem/B", "Medium"},
				{"Strip", "https://codeforces.com/contest/487/problem/B", "Hard"},
				{"Special Segments of Permutation", "https://codeforces.com/contest/1156/problem/E", "Hard"},
				{"Stack Sorting", "https://codeforces.com/contest/911/problem/E", "Hard"},
			}},
			{Name: "String Algorithms", Problems: []problemData{
				{"Good Substrings", "https://codeforces.com/problemset/problem/271/D", "Medium"},
				{"Prefix-Suffix Palindrome", "https://codeforces.com/contest/1326/problem/D2", "Hard"},
				{"Watto and Mechanism", "https://codeforces.com/contest/514/problem/C", "Hard"},
				{"Palindrome Degree", "https://codeforces.com/contest/7/problem/D", "Hard"},
				{"Spy Syndrome 2", "https://codeforces.com/contest/633/problem/C", "Hard"},
				{"Segment Occurrences", "https://codeforces.com/contest/1016/problem/B", "Medium"},
				{"Password", "https://codeforces.com/problemset/problem/126/B", "Medium"},
				{"MUH and Cube Walls", "https://codeforces.com/contest/471/problem/D", "Hard"},
				{"Camp Schedule", "https://codeforces.com/contest/1138/problem/D", "Medium"},
				{"Prefixes and Suffixes", "https://codeforces.com/contest/432/problem/D", "Hard"},
			}},
			{Name: "Trees", Problems: []problemData{
				{"Subordinates", "https://cses.fi/problemset/task/1674", "Easy"},
				{"Tree Matching", "https://cses.fi/problemset/task/1130", "Medium"},
				{"Circumference of a Tree", "https://codeforces.com/gym/102694/problem/A", "Medium"},
				{"Military Problem", "https://codeforces.com/contest/1006/problem/E", "Medium"},
				{"Tree Distances II", "https://cses.fi/problemset/task/1133", "Medium"},
				{"Three Paths on a Tree", "https://codeforces.com/contest/1294/problem/F", "Hard"},
			}},
			{Name: "Graph Algorithms", Problems: []problemData{
				{"Two Buttons", "https://codeforces.com/problemset/problem/520/B", "Easy"},
				{"Party", "https://codeforces.com/problemset/problem/115/A", "Easy"},
				{"Kefa and Park", "https://codeforces.com/problemset/problem/580/C", "Medium"},
				{"Cyclic Components", "https://codeforces.com/problemset/problem/977/E", "Medium"},
				{"Graph Without Long Directed Paths", "https://codeforces.com/contest/1144/problem/F", "Medium"},
				{"Fox And Names", "https://codeforces.com/contest/510/problem/C", "Medium"},
				{"Dijkstra?", "https://codeforces.com/contest/20/problem/C", "Medium"},
				{"Strongly Connected City", "https://codeforces.com/problemset/problem/475/B", "Medium"},
				{"Fair", "https://codeforces.com/contest/986/problem/A", "Medium"},
				{"Monopole Magnets", "https://codeforces.com/contest/1345/problem/D", "Hard"},
				{"Directing Edges", "https://codeforces.com/contest/1385/problem/E", "Hard"},
				{"Greg and Graph", "https://codeforces.com/contest/295/problem/B", "Hard"},
				{"Weights Distributing", "https://codeforces.com/contest/1343/problem/E", "Hard"},
			}},
			{Name: "Matrix Exponentiation", Problems: []problemData{
				{"Plant", "https://codeforces.com/problemset/problem/185/A", "Medium"},
				{"Magic Gems", "https://codeforces.com/contest/1117/problem/D", "Hard"},
				{"Once Again", "https://codeforces.com/contest/582/problem/B", "Medium"},
				{"Decoding Genome", "https://codeforces.com/contest/222/problem/E", "Hard"},
				{"Wet Shark and Blocks", "https://codeforces.com/contest/621/problem/E", "Hard"},
			}},
		},
	}
}
