package database

func blind75Sheet() sheetData {
	return sheetData{
		Name:        "Blind 75 Sheet",
		Slug:        "blind-75",
		Description: "Interview Problems with Video Solutions",
		Topics: []topicData{
			{Name: "Array", Problems: []problemData{
				{"Two Sum", "https://leetcode.com/problems/two-sum/", "Easy"},
				{"Best Time to Buy and Sell Stock", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Easy"},
				{"Contains Duplicate", "https://leetcode.com/problems/contains-duplicate/", "Easy"},
				{"Product of Array Except Self", "https://leetcode.com/problems/product-of-array-except-self/", "Medium"},
				{"Maximum Subarray", "https://leetcode.com/problems/maximum-subarray/", "Medium"},
				{"Maximum Product Subarray", "https://leetcode.com/problems/maximum-product-subarray/", "Medium"},
				{"Find Minimum in Rotated Sorted Array", "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", "Medium"},
				{"Search in Rotated Sorted Array", "https://leetcode.com/problems/search-in-rotated-sorted-array/", "Medium"},
				{"3Sum", "https://leetcode.com/problems/3sum/", "Medium"},
				{"Container With Most Water", "https://leetcode.com/problems/container-with-most-water/", "Medium"},
			}},
			{Name: "Binary", Problems: []problemData{
				{"Sum of Two Integers", "https://leetcode.com/problems/sum-of-two-integers/", "Medium"},
				{"Number of 1 Bits", "https://leetcode.com/problems/number-of-1-bits/", "Easy"},
				{"Counting Bits", "https://leetcode.com/problems/counting-bits/", "Easy"},
				{"Missing Number", "https://leetcode.com/problems/missing-number/", "Easy"},
				{"Reverse Bits", "https://leetcode.com/problems/reverse-bits/", "Easy"},
			}},
			{Name: "Dynamic Programming", Problems: []problemData{
				{"Climbing Stairs", "https://leetcode.com/problems/climbing-stairs/", "Easy"},
				{"Coin Change", "https://leetcode.com/problems/coin-change/", "Medium"},
				{"Longest Increasing Subsequence", "https://leetcode.com/problems/longest-increasing-subsequence/", "Medium"},
				{"Longest Common Subsequence", "https://leetcode.com/problems/longest-common-subsequence/", "Medium"},
				{"Word Break", "https://leetcode.com/problems/word-break/", "Medium"},
				{"Combination Sum IV", "https://leetcode.com/problems/combination-sum-iv/", "Medium"},
				{"House Robber", "https://leetcode.com/problems/house-robber/", "Medium"},
				{"House Robber II", "https://leetcode.com/problems/house-robber-ii/", "Medium"},
				{"Decode Ways", "https://leetcode.com/problems/decode-ways/", "Medium"},
				{"Unique Paths", "https://leetcode.com/problems/unique-paths/", "Medium"},
				{"Jump Game", "https://leetcode.com/problems/jump-game/", "Medium"},
			}},
			{Name: "Graph", Problems: []problemData{
				{"Clone Graph", "https://leetcode.com/problems/clone-graph/", "Medium"},
				{"Course Schedule", "https://leetcode.com/problems/course-schedule/", "Medium"},
				{"Pacific Atlantic Water Flow", "https://leetcode.com/problems/pacific-atlantic-water-flow/", "Medium"},
				{"Number of Islands", "https://leetcode.com/problems/number-of-islands/", "Medium"},
				{"Longest Consecutive Sequence", "https://leetcode.com/problems/longest-consecutive-sequence/", "Medium"},
				{"Alien Dictionary", "https://leetcode.com/problems/alien-dictionary/", "Hard"},
				{"Graph Valid Tree", "https://leetcode.com/problems/graph-valid-tree/", "Medium"},
				{"Number of Connected Components", "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", "Medium"},
			}},
			{Name: "Interval", Problems: []problemData{
				{"Insert Interval", "https://leetcode.com/problems/insert-interval/", "Medium"},
				{"Merge Intervals", "https://leetcode.com/problems/merge-intervals/", "Medium"},
				{"Non-overlapping Intervals", "https://leetcode.com/problems/non-overlapping-intervals/", "Medium"},
				{"Meeting Rooms", "https://leetcode.com/problems/meeting-rooms/", "Easy"},
				{"Meeting Rooms II", "https://leetcode.com/problems/meeting-rooms-ii/", "Medium"},
			}},
			{Name: "Linked List", Problems: []problemData{
				{"Reverse Linked List", "https://leetcode.com/problems/reverse-linked-list/", "Easy"},
				{"Linked List Cycle", "https://leetcode.com/problems/linked-list-cycle/", "Easy"},
				{"Merge Two Sorted Lists", "https://leetcode.com/problems/merge-two-sorted-lists/", "Easy"},
				{"Merge K Sorted Lists", "https://leetcode.com/problems/merge-k-sorted-lists/", "Hard"},
				{"Remove Nth Node From End of List", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "Medium"},
				{"Reorder List", "https://leetcode.com/problems/reorder-list/", "Medium"},
			}},
			{Name: "Matrix", Problems: []problemData{
				{"Set Matrix Zeroes", "https://leetcode.com/problems/set-matrix-zeroes/", "Medium"},
				{"Spiral Matrix", "https://leetcode.com/problems/spiral-matrix/", "Medium"},
				{"Rotate Image", "https://leetcode.com/problems/rotate-image/", "Medium"},
				{"Word Search", "https://leetcode.com/problems/word-search/", "Medium"},
			}},
			{Name: "String", Problems: []problemData{
				{"Longest Substring Without Repeating Characters", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "Medium"},
				{"Longest Repeating Character Replacement", "https://leetcode.com/problems/longest-repeating-character-replacement/", "Medium"},
				{"Minimum Window Substring", "https://leetcode.com/problems/minimum-window-substring/", "Hard"},
				{"Valid Anagram", "https://leetcode.com/problems/valid-anagram/", "Easy"},
				{"Group Anagrams", "https://leetcode.com/problems/group-anagrams/", "Medium"},
				{"Valid Parentheses", "https://leetcode.com/problems/valid-parentheses/", "Easy"},
				{"Palindromic Substrings", "https://leetcode.com/problems/palindromic-substrings/", "Medium"},
				{"Longest Palindromic Substring", "https://leetcode.com/problems/longest-palindromic-substring/", "Medium"},
				{"Encode and Decode Strings", "https://leetcode.com/problems/encode-and-decode-strings/", "Medium"},
			}},
			{Name: "Tree", Problems: []problemData{
				{"Maximum Depth of Binary Tree", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "Easy"},
				{"Same Tree", "https://leetcode.com/problems/same-tree/", "Easy"},
				{"Invert Binary Tree", "https://leetcode.com/problems/invert-binary-tree/", "Easy"},
				{"Binary Tree Maximum Path Sum", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "Hard"},
				{"Binary Tree Level Order Traversal", "https://leetcode.com/problems/binary-tree-level-order-traversal/", "Medium"},
				{"Serialize and Deserialize Binary Tree", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "Hard"},
				{"Subtree of Another Tree", "https://leetcode.com/problems/subtree-of-another-tree/", "Easy"},
				{"Construct Binary Tree from Preorder and Inorder", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", "Medium"},
				{"Validate Binary Search Tree", "https://leetcode.com/problems/validate-binary-search-tree/", "Medium"},
				{"Kth Smallest Element in a BST", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "Medium"},
				{"Lowest Common Ancestor of BST", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", "Medium"},
				{"Implement Trie", "https://leetcode.com/problems/implement-trie-prefix-tree/", "Medium"},
				{"Design Add and Search Words", "https://leetcode.com/problems/design-add-and-search-words-data-structure/", "Medium"},
			}},
			{Name: "Heap", Problems: []problemData{
				{"Top K Frequent Elements", "https://leetcode.com/problems/top-k-frequent-elements/", "Medium"},
				{"Find Median from Data Stream", "https://leetcode.com/problems/find-median-from-data-stream/", "Hard"},
			}},
		},
	}
}
