package database

func striver79Sheet() sheetData {
	return sheetData{
		Name:        "Striver 79 Sheet",
		Slug:        "striver-79",
		Description: "Last Minute Preparation",
		Topics: []topicData{
			{Name: "Arrays", Problems: []problemData{
				{"Set Matrix Zeroes", "https://leetcode.com/problems/set-matrix-zeroes/", "Medium"},
				{"Kadane's Algorithm", "https://leetcode.com/problems/maximum-subarray/", "Medium"},
				{"Sort an array of 0's 1's and 2's", "https://leetcode.com/problems/sort-colors/", "Medium"},
				{"Next Permutation", "https://leetcode.com/problems/next-permutation/", "Medium"},
				{"Stock Buy and Sell", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "Easy"},
				{"Rotate Matrix", "https://leetcode.com/problems/rotate-image/", "Medium"},
				{"Merge Overlapping Subintervals", "https://leetcode.com/problems/merge-intervals/", "Medium"},
				{"Find the Duplicate Number", "https://leetcode.com/problems/find-the-duplicate-number/", "Medium"},
				{"Majority Element (>N/2)", "https://leetcode.com/problems/majority-element/", "Easy"},
				{"Majority Element (>N/3)", "https://leetcode.com/problems/majority-element-ii/", "Medium"},
				{"Two Sum", "https://leetcode.com/problems/two-sum/", "Easy"},
				{"4 Sum", "https://leetcode.com/problems/4sum/", "Medium"},
				{"Longest Consecutive Sequence", "https://leetcode.com/problems/longest-consecutive-sequence/", "Medium"},
				{"Longest Substring Without Repeating Characters", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "Medium"},
			}},
			{Name: "Linked List", Problems: []problemData{
				{"Reverse Linked List", "https://leetcode.com/problems/reverse-linked-list/", "Easy"},
				{"Middle of Linked List", "https://leetcode.com/problems/middle-of-the-linked-list/", "Easy"},
				{"Merge Two Sorted Lists", "https://leetcode.com/problems/merge-two-sorted-lists/", "Easy"},
				{"Remove Nth Node From End", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "Medium"},
				{"Add Two Numbers", "https://leetcode.com/problems/add-two-numbers/", "Medium"},
				{"Detect Cycle in LL", "https://leetcode.com/problems/linked-list-cycle/", "Easy"},
				{"Starting Point of Cycle", "https://leetcode.com/problems/linked-list-cycle-ii/", "Medium"},
				{"Palindrome Linked List", "https://leetcode.com/problems/palindrome-linked-list/", "Easy"},
				{"Reverse Nodes in k-Group", "https://leetcode.com/problems/reverse-nodes-in-k-group/", "Hard"},
				{"Flatten a Linked List", "https://www.geeksforgeeks.org/flattening-a-linked-list/", "Medium"},
				{"Intersection of Two Linked Lists", "https://leetcode.com/problems/intersection-of-two-linked-lists/", "Easy"},
				{"Rotate List", "https://leetcode.com/problems/rotate-list/", "Medium"},
			}},
			{Name: "Greedy", Problems: []problemData{
				{"N Meetings in One Room", "https://www.geeksforgeeks.org/find-maximum-meetings-in-one-room/", "Easy"},
				{"Minimum Platforms", "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/", "Medium"},
				{"Job Sequencing Problem", "https://www.geeksforgeeks.org/job-sequencing-problem/", "Medium"},
				{"Fractional Knapsack", "https://www.geeksforgeeks.org/fractional-knapsack-problem/", "Medium"},
			}},
			{Name: "Recursion & Backtracking", Problems: []problemData{
				{"Combination Sum", "https://leetcode.com/problems/combination-sum/", "Medium"},
				{"Combination Sum II", "https://leetcode.com/problems/combination-sum-ii/", "Medium"},
				{"Subsets II", "https://leetcode.com/problems/subsets-ii/", "Medium"},
				{"Permutations", "https://leetcode.com/problems/permutations/", "Medium"},
				{"Palindrome Partitioning", "https://leetcode.com/problems/palindrome-partitioning/", "Medium"},
				{"N Queens", "https://leetcode.com/problems/n-queens/", "Hard"},
				{"Sudoku Solver", "https://leetcode.com/problems/sudoku-solver/", "Hard"},
			}},
			{Name: "Binary Search", Problems: []problemData{
				{"Search in Rotated Sorted Array", "https://leetcode.com/problems/search-in-rotated-sorted-array/", "Medium"},
				{"Median of Two Sorted Arrays", "https://leetcode.com/problems/median-of-two-sorted-arrays/", "Hard"},
				{"Single Element in Sorted Array", "https://leetcode.com/problems/single-element-in-a-sorted-array/", "Medium"},
				{"Kth Element of Two Sorted Arrays", "https://www.geeksforgeeks.org/k-th-element-two-sorted-arrays/", "Medium"},
				{"Allocate Minimum Number of Pages", "https://www.geeksforgeeks.org/allocate-minimum-number-pages/", "Hard"},
				{"Aggressive Cows", "https://www.spoj.com/problems/AGGRCOW/", "Hard"},
			}},
			{Name: "Stack & Queue", Problems: []problemData{
				{"Valid Parentheses", "https://leetcode.com/problems/valid-parentheses/", "Easy"},
				{"Next Greater Element", "https://leetcode.com/problems/next-greater-element-i/", "Easy"},
				{"LRU Cache", "https://leetcode.com/problems/lru-cache/", "Medium"},
				{"Largest Rectangle in Histogram", "https://leetcode.com/problems/largest-rectangle-in-histogram/", "Hard"},
				{"Sliding Window Maximum", "https://leetcode.com/problems/sliding-window-maximum/", "Hard"},
				{"Min Stack", "https://leetcode.com/problems/min-stack/", "Medium"},
			}},
			{Name: "Binary Tree", Problems: []problemData{
				{"Inorder Traversal", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "Easy"},
				{"Level Order Traversal", "https://leetcode.com/problems/binary-tree-level-order-traversal/", "Medium"},
				{"Maximum Depth", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "Easy"},
				{"Diameter of Binary Tree", "https://leetcode.com/problems/diameter-of-binary-tree/", "Easy"},
				{"Balanced Binary Tree", "https://leetcode.com/problems/balanced-binary-tree/", "Easy"},
				{"LCA of Binary Tree", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "Medium"},
				{"Same Tree", "https://leetcode.com/problems/same-tree/", "Easy"},
				{"Binary Tree Maximum Path Sum", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "Hard"},
				{"Zig Zag Level Order", "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "Medium"},
			}},
			{Name: "Binary Search Tree", Problems: []problemData{
				{"Search in a BST", "https://leetcode.com/problems/search-in-a-binary-search-tree/", "Easy"},
				{"Validate BST", "https://leetcode.com/problems/validate-binary-search-tree/", "Medium"},
				{"LCA of BST", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", "Medium"},
				{"Kth Smallest Element in BST", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "Medium"},
			}},
			{Name: "Graph", Problems: []problemData{
				{"Number of Islands", "https://leetcode.com/problems/number-of-islands/", "Medium"},
				{"Clone Graph", "https://leetcode.com/problems/clone-graph/", "Medium"},
				{"Course Schedule (Topological Sort)", "https://leetcode.com/problems/course-schedule/", "Medium"},
				{"Dijkstra's Algorithm", "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/", "Medium"},
			}},
			{Name: "Dynamic Programming", Problems: []problemData{
				{"Longest Increasing Subsequence", "https://leetcode.com/problems/longest-increasing-subsequence/", "Medium"},
				{"Longest Common Subsequence", "https://leetcode.com/problems/longest-common-subsequence/", "Medium"},
				{"0-1 Knapsack", "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/", "Medium"},
				{"Edit Distance", "https://leetcode.com/problems/edit-distance/", "Hard"},
				{"Max Product Subarray", "https://leetcode.com/problems/maximum-product-subarray/", "Medium"},
				{"Coin Change", "https://leetcode.com/problems/coin-change/", "Medium"},
				{"Subset Sum", "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/", "Medium"},
				{"Matrix Chain Multiplication", "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/", "Hard"},
			}},
			{Name: "Trie", Problems: []problemData{
				{"Implement Trie", "https://leetcode.com/problems/implement-trie-prefix-tree/", "Medium"},
				{"Word Search II", "https://leetcode.com/problems/word-search-ii/", "Hard"},
			}},
		},
	}
}
